import { Router } from "express";
import { RowDataPacket } from "mysql2";
import { isPublicContentLocale } from "../../config/public-content.config";
import { pool } from "../../db";
import { buildAttachmentUrl } from "../../helper/attachment.helper";
import { sendError, sendSuccess } from "../../helper/api-response.helper";

const router=Router();
const scope=(locale:unknown)=>{const company=Number(process.env.PUBLIC_CMS_COMPANY_ID);return Number.isSafeInteger(company)&&company>0&&isPublicContentLocale(locale)?{company,locale}:null};
const image=(row:any,prefix:string)=>row[`${prefix}_path`]?{asset_url:buildAttachmentUrl(row[`${prefix}_path`]),original_url:buildAttachmentUrl(row[`${prefix}_path`]),name:row[`${prefix}_name`]??"",width:row[`${prefix}_width`]??null,height:row[`${prefix}_height`]??null}:null;
const baseSelect=`SELECT a.id_article,a.article_is_featured,a.article_is_sticky,a.article_published_at,a.created,a.updated,i.article_slug,i.article_title,i.article_excerpt,i.article_body,i.article_meta_title,i.article_meta_description,i.article_canonical_url,i.article_og_title,i.article_og_description,i.article_schema_json,th.storage_path thumbnail_path,th.name thumbnail_name,th.width thumbnail_width,th.height thumbnail_height,og.storage_path og_path,og.name og_name,og.width og_width,og.height og_height FROM article a JOIN article_i18n i ON i.id_article=a.id_article AND i.id_master_comp=a.id_master_comp LEFT JOIN article_attachment ath ON ath.id_article=a.id_article AND ath.article_attachment_role='thumbnail' AND ath.article_attachment_sort_order=0 AND ath.article_attachment_is_public=1 LEFT JOIN attachment th ON th.id_attachment=ath.id_attachment AND th.attachment_status=1 AND th.deleted_at IS NULL LEFT JOIN article_attachment aog ON aog.id_article=a.id_article AND aog.article_attachment_role='og' AND aog.article_attachment_sort_order=0 AND aog.article_attachment_is_public=1 LEFT JOIN attachment og ON og.id_attachment=aog.id_attachment AND og.attachment_status=1 AND og.deleted_at IS NULL`;
const publicWhere=`a.id_master_comp=? AND i.article_locale=? AND i.article_i18n_status=1 AND a.article_status='published' AND a.article_deleted_at IS NULL AND (a.article_published_at IS NULL OR a.article_published_at<=NOW()) AND (a.article_unpublished_at IS NULL OR a.article_unpublished_at>NOW())`;
const dto=(row:any,detail=false)=>({id:Number(row.id_article),title:row.article_title,slug:row.article_slug,description:row.article_excerpt??"",content:detail?row.article_body:"",status:true,meta_title:row.article_meta_title??row.article_title,meta_description:row.article_meta_description??row.article_excerpt??"",canonical_url:row.article_canonical_url??"",og_title:row.article_og_title??row.article_meta_title??row.article_title,og_description:row.article_og_description??row.article_meta_description??row.article_excerpt??"",schema_json:row.article_schema_json?JSON.parse(row.article_schema_json):null,blog_thumbnail:image(row,"thumbnail"),blog_meta_image:image(row,"og")??image(row,"thumbnail"),categories:[],tags:[],is_featured:Boolean(row.article_is_featured),is_sticky:Boolean(row.article_is_sticky),created_by:{name:"MATEX",profile_image:null},created_at:row.article_published_at??row.created,updated_at:row.updated});
router.get("/api/public/articles/:locale",async(req,res)=>{res.setHeader("Cache-Control","no-store");const s=scope(req.params.locale);if(!s)return sendError(res,404,"ARTICLES_NOT_FOUND","Articles not found");const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Math.max(1,Number(req.query.limit??req.query.paginate)||12)),search=String(req.query.search??"").trim(),like=`%${search}%`;try{const[counts]=await pool.query<RowDataPacket[]>(`SELECT COUNT(*) total FROM article a JOIN article_i18n i ON i.id_article=a.id_article AND i.id_master_comp=a.id_master_comp WHERE ${publicWhere} AND (?='' OR i.article_title LIKE ? OR i.article_excerpt LIKE ?)`,[s.company,s.locale,search,like,like]);const[rows]=await pool.query<RowDataPacket[]>(`${baseSelect} WHERE ${publicWhere} AND (?='' OR i.article_title LIKE ? OR i.article_excerpt LIKE ?) ORDER BY a.article_is_sticky DESC,COALESCE(a.article_published_at,a.created) DESC LIMIT ? OFFSET ?`,[s.company,s.locale,search,like,like,limit,(page-1)*limit]);return sendSuccess(res,200,"ARTICLES_FOUND","Articles loaded",{data:rows.map(r=>dto(r)),total:Number(counts[0]?.total??0),current_page:page,per_page:limit});}catch(error){console.error("[Public article] list failed",error);return sendError(res,500,"ARTICLES_UNAVAILABLE","Unable to load articles")}});
router.get("/api/public/articles/:locale/:slug",async(req,res)=>{res.setHeader("Cache-Control","no-store");const s=scope(req.params.locale);if(!s)return sendError(res,404,"ARTICLE_NOT_FOUND","Article not found");try{const[rows]=await pool.query<RowDataPacket[]>(`${baseSelect} WHERE ${publicWhere} AND i.article_slug=? LIMIT 1`,[s.company,s.locale,req.params.slug]);if(!rows.length)return sendError(res,404,"ARTICLE_NOT_FOUND","Article not found");return sendSuccess(res,200,"ARTICLE_FOUND","Article loaded",dto(rows[0],true));}catch(error){console.error("[Public article] detail failed",error);return sendError(res,500,"ARTICLE_UNAVAILABLE","Unable to load article")}});
export default router;
