CREATE TABLE `product_catalog` (
  `id_product` int NOT NULL AUTO_INCREMENT,
  `id_master_comp` int NOT NULL,
  `product_key` varchar(120) NOT NULL,
  `product_sku` varchar(120) NOT NULL,
  `product_type` varchar(30) NOT NULL DEFAULT 'physical',
  `product_status` varchar(20) NOT NULL DEFAULT 'draft',
  `product_unit` varchar(40) DEFAULT NULL,
  `product_barcode` varchar(120) DEFAULT NULL,
  `product_manufacturer_code` varchar(120) DEFAULT NULL,
  `product_country_origin` varchar(100) DEFAULT NULL,
  `product_hs_code` varchar(50) DEFAULT NULL,
  `product_weight_grams` decimal(12,3) DEFAULT NULL,
  `product_length_mm` decimal(12,3) DEFAULT NULL,
  `product_width_mm` decimal(12,3) DEFAULT NULL,
  `product_height_mm` decimal(12,3) DEFAULT NULL,
  `product_min_order_qty` decimal(12,3) NOT NULL DEFAULT 1,
  `product_lead_time_days` int DEFAULT NULL,
  `product_manage_stock` tinyint(1) NOT NULL DEFAULT 0,
  `product_stock_quantity` decimal(14,3) DEFAULT NULL,
  `product_stock_status` varchar(30) NOT NULL DEFAULT 'in_stock',
  `product_price_visibility` varchar(30) NOT NULL DEFAULT 'contact',
  `product_internal_commerce_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `product_is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `product_sort_order` int NOT NULL DEFAULT 0,
  `id_created_by` int DEFAULT NULL,
  `id_updated_by` int DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `product_deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE KEY `uq_product_company_id` (`id_product`,`id_master_comp`),
  UNIQUE KEY `uq_product_company_key` (`id_master_comp`,`product_key`),
  UNIQUE KEY `uq_product_company_sku` (`id_master_comp`,`product_sku`),
  KEY `idx_product_public` (`id_master_comp`,`product_status`,`product_sort_order`),
  CONSTRAINT `fk_product_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `fk_product_created_by` FOREIGN KEY (`id_created_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_product_updated_by` FOREIGN KEY (`id_updated_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_product_type` CHECK (`product_type` IN ('physical','service','digital')),
  CONSTRAINT `chk_product_status` CHECK (`product_status` IN ('draft','published','archived')),
  CONSTRAINT `chk_product_stock_status` CHECK (`product_stock_status` IN ('in_stock','out_of_stock','preorder','made_to_order')),
  CONSTRAINT `chk_product_price_visibility` CHECK (`product_price_visibility` IN ('displayed','contact','hidden'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_catalog_i18n` (
  `id_product_i18n` int NOT NULL AUTO_INCREMENT,
  `id_product` int NOT NULL,
  `id_master_comp` int NOT NULL,
  `product_locale` varchar(20) NOT NULL,
  `product_slug` varchar(255) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_short_description` text DEFAULT NULL,
  `product_description` longtext DEFAULT NULL,
  `product_specifications_json` json DEFAULT NULL,
  `product_meta_title` varchar(255) DEFAULT NULL,
  `product_meta_description` varchar(500) DEFAULT NULL,
  `product_canonical_url` varchar(1000) DEFAULT NULL,
  `product_og_title` varchar(255) DEFAULT NULL,
  `product_og_description` varchar(500) DEFAULT NULL,
  `product_i18n_status` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_product_i18n`),
  UNIQUE KEY `uq_product_i18n_locale` (`id_product`,`product_locale`),
  UNIQUE KEY `uq_product_i18n_slug` (`id_master_comp`,`product_locale`,`product_slug`),
  CONSTRAINT `fk_product_i18n_parent` FOREIGN KEY (`id_product`,`id_master_comp`) REFERENCES `product_catalog` (`id_product`,`id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_catalog_category` (
  `id_product` int NOT NULL,
  `id_product_category` int NOT NULL,
  `id_master_comp` int NOT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `sort_order` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_product`,`id_product_category`),
  KEY `idx_product_category_product` (`id_product_category`,`id_master_comp`),
  CONSTRAINT `fk_product_category_product` FOREIGN KEY (`id_product`,`id_master_comp`) REFERENCES `product_catalog` (`id_product`,`id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_product_category_category` FOREIGN KEY (`id_product_category`,`id_master_comp`) REFERENCES `product_category` (`id_product_category`,`id_master_comp`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_catalog_attachment` (
  `id_product_attachment` int NOT NULL AUTO_INCREMENT,
  `id_product` int NOT NULL,
  `id_master_comp` int NOT NULL,
  `id_attachment` int NOT NULL,
  `product_attachment_role` varchar(30) NOT NULL,
  `product_attachment_sort_order` int NOT NULL DEFAULT 0,
  `product_attachment_is_public` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id_product_attachment`),
  UNIQUE KEY `uq_product_attachment_role` (`id_product`,`product_attachment_role`,`product_attachment_sort_order`),
  KEY `idx_product_attachment_media` (`id_attachment`),
  CONSTRAINT `fk_product_attachment_parent` FOREIGN KEY (`id_product`,`id_master_comp`) REFERENCES `product_catalog` (`id_product`,`id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_product_attachment_media` FOREIGN KEY (`id_attachment`) REFERENCES `attachment` (`id_attachment`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_product_attachment_role` CHECK (`product_attachment_role` IN ('thumbnail','gallery','og','size_chart','document'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_catalog_price` (
  `id_product_price` int NOT NULL AUTO_INCREMENT,
  `id_product` int NOT NULL,
  `id_master_comp` int NOT NULL,
  `product_price_type` varchar(40) NOT NULL,
  `product_price_label` varchar(120) DEFAULT NULL,
  `product_price_currency` char(3) NOT NULL DEFAULT 'IDR',
  `product_price_amount` decimal(18,2) NOT NULL,
  `product_price_compare_at` decimal(18,2) DEFAULT NULL,
  `product_price_min_qty` decimal(12,3) DEFAULT NULL,
  `product_price_max_qty` decimal(12,3) DEFAULT NULL,
  `product_price_starts_at` datetime DEFAULT NULL,
  `product_price_ends_at` datetime DEFAULT NULL,
  `product_price_is_public` tinyint(1) NOT NULL DEFAULT 0,
  `product_price_is_active` tinyint(1) NOT NULL DEFAULT 1,
  `product_price_sort_order` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_product_price`),
  KEY `idx_product_price_parent` (`id_product`,`id_master_comp`),
  CONSTRAINT `fk_product_price_parent` FOREIGN KEY (`id_product`,`id_master_comp`) REFERENCES `product_catalog` (`id_product`,`id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_catalog_marketplace` (
  `id_product_marketplace` int NOT NULL AUTO_INCREMENT,
  `id_product` int NOT NULL,
  `id_master_comp` int NOT NULL,
  `product_marketplace_provider` varchar(50) NOT NULL,
  `product_marketplace_label` varchar(120) DEFAULT NULL,
  `product_marketplace_url` varchar(1000) NOT NULL,
  `product_marketplace_sku` varchar(120) DEFAULT NULL,
  `product_marketplace_price` decimal(18,2) DEFAULT NULL,
  `product_marketplace_currency` char(3) NOT NULL DEFAULT 'IDR',
  `product_marketplace_is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `product_marketplace_is_active` tinyint(1) NOT NULL DEFAULT 1,
  `product_marketplace_sort_order` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_product_marketplace`),
  KEY `idx_product_marketplace_parent` (`id_product`,`id_master_comp`),
  CONSTRAINT `fk_product_marketplace_parent` FOREIGN KEY (`id_product`,`id_master_comp`) REFERENCES `product_catalog` (`id_product`,`id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
