-- Public contact channels, inquiry topics, inquiries, and localized FAQ.
-- Review and apply to the development database before enabling their API/UI.

CREATE TABLE `public_contact_channel` (
  `id_public_contact_channel` int(11) NOT NULL AUTO_INCREMENT,
  `id_master_comp` int(11) NOT NULL,
  `public_contact_channel_key` varchar(100) NOT NULL,
  `public_contact_channel_type` varchar(30) NOT NULL,
  `public_contact_channel_value` varchar(500) NOT NULL,
  `public_contact_channel_url` varchar(1000) DEFAULT NULL,
  `public_contact_channel_is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `public_contact_channel_is_public` tinyint(1) NOT NULL DEFAULT 1,
  `public_contact_channel_sort_order` int(11) NOT NULL DEFAULT 0,
  `public_contact_channel_settings_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`public_contact_channel_settings_json`)),
  `id_created_by` int(11) DEFAULT NULL,
  `id_updated_by` int(11) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `public_contact_channel_deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_public_contact_channel`),
  UNIQUE KEY `uq_public_contact_channel_id_company` (`id_public_contact_channel`, `id_master_comp`),
  UNIQUE KEY `uq_public_contact_channel_company_key` (`id_master_comp`, `public_contact_channel_key`),
  KEY `idx_public_contact_channel_public` (`id_master_comp`, `public_contact_channel_is_public`, `public_contact_channel_sort_order`),
  KEY `idx_public_contact_channel_created_by` (`id_created_by`),
  KEY `idx_public_contact_channel_updated_by` (`id_updated_by`),
  CONSTRAINT `fk_public_contact_channel_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `fk_public_contact_channel_created_by` FOREIGN KEY (`id_created_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_public_contact_channel_updated_by` FOREIGN KEY (`id_updated_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_public_contact_channel_type` CHECK (`public_contact_channel_type` IN ('whatsapp', 'email', 'phone', 'social', 'website', 'other')),
  CONSTRAINT `chk_public_contact_channel_primary` CHECK (`public_contact_channel_is_primary` IN (0, 1)),
  CONSTRAINT `chk_public_contact_channel_public` CHECK (`public_contact_channel_is_public` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `public_contact_channel_i18n` (
  `id_public_contact_channel_i18n` int(11) NOT NULL AUTO_INCREMENT,
  `id_public_contact_channel` int(11) NOT NULL,
  `id_master_comp` int(11) NOT NULL,
  `public_contact_channel_locale` varchar(20) NOT NULL,
  `public_contact_channel_label` varchar(255) NOT NULL,
  `public_contact_channel_description` varchar(500) DEFAULT NULL,
  `public_contact_channel_i18n_status` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_public_contact_channel_i18n`),
  UNIQUE KEY `uq_public_contact_channel_i18n_locale` (`id_public_contact_channel`, `public_contact_channel_locale`),
  KEY `idx_public_contact_channel_i18n_company_locale` (`id_master_comp`, `public_contact_channel_locale`, `public_contact_channel_i18n_status`),
  KEY `idx_public_contact_channel_i18n_channel_company` (`id_public_contact_channel`, `id_master_comp`),
  CONSTRAINT `fk_public_contact_channel_i18n_channel_company` FOREIGN KEY (`id_public_contact_channel`, `id_master_comp`) REFERENCES `public_contact_channel` (`id_public_contact_channel`, `id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_public_contact_channel_i18n_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `chk_public_contact_channel_i18n_status` CHECK (`public_contact_channel_i18n_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contact_inquiry_topic` (
  `id_contact_inquiry_topic` int(11) NOT NULL AUTO_INCREMENT,
  `id_master_comp` int(11) NOT NULL,
  `contact_inquiry_topic_key` varchar(100) NOT NULL,
  `contact_inquiry_topic_recipient_email` varchar(255) DEFAULT NULL,
  `contact_inquiry_topic_sort_order` int(11) NOT NULL DEFAULT 0,
  `contact_inquiry_topic_status` tinyint(1) NOT NULL DEFAULT 1,
  `id_created_by` int(11) DEFAULT NULL,
  `id_updated_by` int(11) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_contact_inquiry_topic`),
  UNIQUE KEY `uq_contact_inquiry_topic_id_company` (`id_contact_inquiry_topic`, `id_master_comp`),
  UNIQUE KEY `uq_contact_inquiry_topic_company_key` (`id_master_comp`, `contact_inquiry_topic_key`),
  KEY `idx_contact_inquiry_topic_public` (`id_master_comp`, `contact_inquiry_topic_status`, `contact_inquiry_topic_sort_order`),
  CONSTRAINT `fk_contact_inquiry_topic_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `fk_contact_inquiry_topic_created_by` FOREIGN KEY (`id_created_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_contact_inquiry_topic_updated_by` FOREIGN KEY (`id_updated_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_contact_inquiry_topic_status` CHECK (`contact_inquiry_topic_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contact_inquiry_topic_i18n` (
  `id_contact_inquiry_topic_i18n` int(11) NOT NULL AUTO_INCREMENT,
  `id_contact_inquiry_topic` int(11) NOT NULL,
  `id_master_comp` int(11) NOT NULL,
  `contact_inquiry_topic_locale` varchar(20) NOT NULL,
  `contact_inquiry_topic_label` varchar(255) NOT NULL,
  `contact_inquiry_topic_i18n_status` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_contact_inquiry_topic_i18n`),
  UNIQUE KEY `uq_contact_inquiry_topic_i18n_locale` (`id_contact_inquiry_topic`, `contact_inquiry_topic_locale`),
  KEY `idx_contact_inquiry_topic_i18n_company_locale` (`id_master_comp`, `contact_inquiry_topic_locale`, `contact_inquiry_topic_i18n_status`),
  KEY `idx_contact_inquiry_topic_i18n_topic_company` (`id_contact_inquiry_topic`, `id_master_comp`),
  CONSTRAINT `fk_contact_inquiry_topic_i18n_topic_company` FOREIGN KEY (`id_contact_inquiry_topic`, `id_master_comp`) REFERENCES `contact_inquiry_topic` (`id_contact_inquiry_topic`, `id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_contact_inquiry_topic_i18n_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `chk_contact_inquiry_topic_i18n_status` CHECK (`contact_inquiry_topic_i18n_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contact_inquiry` (
  `id_contact_inquiry` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_master_comp` int(11) NOT NULL,
  `id_contact_inquiry_topic` int(11) DEFAULT NULL,
  `contact_inquiry_name` varchar(255) NOT NULL,
  `contact_inquiry_email` varchar(255) DEFAULT NULL,
  `contact_inquiry_phone` varchar(50) DEFAULT NULL,
  `contact_inquiry_message` text NOT NULL,
  `contact_inquiry_locale` varchar(20) NOT NULL DEFAULT 'id-ID',
  `contact_inquiry_source_path` varchar(500) DEFAULT NULL,
  `contact_inquiry_referrer` varchar(1000) DEFAULT NULL,
  `contact_inquiry_user_agent` varchar(1000) DEFAULT NULL,
  `contact_inquiry_ip_hash` binary(32) DEFAULT NULL,
  `contact_inquiry_consent_at` datetime DEFAULT NULL,
  `contact_inquiry_status` varchar(30) NOT NULL DEFAULT 'new',
  `id_assigned_to` int(11) DEFAULT NULL,
  `contact_inquiry_internal_note` text DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `contact_inquiry_closed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_contact_inquiry`),
  KEY `idx_contact_inquiry_company_status_created` (`id_master_comp`, `contact_inquiry_status`, `created`),
  KEY `idx_contact_inquiry_topic_company` (`id_contact_inquiry_topic`, `id_master_comp`),
  KEY `idx_contact_inquiry_assigned_to` (`id_assigned_to`),
  CONSTRAINT `fk_contact_inquiry_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `fk_contact_inquiry_selected_topic_company` FOREIGN KEY (`id_contact_inquiry_topic`, `id_master_comp`) REFERENCES `contact_inquiry_topic` (`id_contact_inquiry_topic`, `id_master_comp`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_contact_inquiry_assigned_to` FOREIGN KEY (`id_assigned_to`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_contact_inquiry_locale` CHECK (`contact_inquiry_locale` IN ('id-ID', 'en-US')),
  CONSTRAINT `chk_contact_inquiry_status` CHECK (`contact_inquiry_status` IN ('new', 'in_progress', 'resolved', 'spam', 'closed')),
  CONSTRAINT `chk_contact_inquiry_contact` CHECK (`contact_inquiry_email` IS NOT NULL OR `contact_inquiry_phone` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faq_category` (
  `id_faq_category` int(11) NOT NULL AUTO_INCREMENT,
  `id_master_comp` int(11) NOT NULL,
  `faq_category_key` varchar(100) NOT NULL,
  `faq_category_sort_order` int(11) NOT NULL DEFAULT 0,
  `faq_category_status` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `faq_category_deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_faq_category`),
  UNIQUE KEY `uq_faq_category_id_company` (`id_faq_category`, `id_master_comp`),
  UNIQUE KEY `uq_faq_category_company_key` (`id_master_comp`, `faq_category_key`),
  KEY `idx_faq_category_public` (`id_master_comp`, `faq_category_status`, `faq_category_sort_order`),
  CONSTRAINT `fk_faq_category_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `chk_faq_category_status` CHECK (`faq_category_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faq_category_i18n` (
  `id_faq_category_i18n` int(11) NOT NULL AUTO_INCREMENT,
  `id_faq_category` int(11) NOT NULL,
  `id_master_comp` int(11) NOT NULL,
  `faq_category_locale` varchar(20) NOT NULL,
  `faq_category_name` varchar(255) NOT NULL,
  `faq_category_i18n_status` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_faq_category_i18n`),
  UNIQUE KEY `uq_faq_category_i18n_locale` (`id_faq_category`, `faq_category_locale`),
  KEY `idx_faq_category_i18n_company_locale` (`id_master_comp`, `faq_category_locale`, `faq_category_i18n_status`),
  KEY `idx_faq_category_i18n_category_company` (`id_faq_category`, `id_master_comp`),
  CONSTRAINT `fk_faq_category_i18n_category_company` FOREIGN KEY (`id_faq_category`, `id_master_comp`) REFERENCES `faq_category` (`id_faq_category`, `id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_faq_category_i18n_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `chk_faq_category_i18n_status` CHECK (`faq_category_i18n_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faq` (
  `id_faq` int(11) NOT NULL AUTO_INCREMENT,
  `id_master_comp` int(11) NOT NULL,
  `id_faq_category` int(11) DEFAULT NULL,
  `faq_key` varchar(100) NOT NULL,
  `faq_sort_order` int(11) NOT NULL DEFAULT 0,
  `faq_status` tinyint(1) NOT NULL DEFAULT 1,
  `id_created_by` int(11) DEFAULT NULL,
  `id_updated_by` int(11) DEFAULT NULL,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `faq_deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_faq`),
  UNIQUE KEY `uq_faq_id_company` (`id_faq`, `id_master_comp`),
  UNIQUE KEY `uq_faq_company_key` (`id_master_comp`, `faq_key`),
  KEY `idx_faq_public` (`id_master_comp`, `faq_status`, `faq_sort_order`),
  KEY `idx_faq_category_company` (`id_faq_category`, `id_master_comp`),
  CONSTRAINT `fk_faq_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `fk_faq_selected_category_company` FOREIGN KEY (`id_faq_category`, `id_master_comp`) REFERENCES `faq_category` (`id_faq_category`, `id_master_comp`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_faq_created_by` FOREIGN KEY (`id_created_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_faq_updated_by` FOREIGN KEY (`id_updated_by`) REFERENCES `admin_acct` (`id_admin_acct`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_faq_status` CHECK (`faq_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `faq_i18n` (
  `id_faq_i18n` int(11) NOT NULL AUTO_INCREMENT,
  `id_faq` int(11) NOT NULL,
  `id_master_comp` int(11) NOT NULL,
  `faq_locale` varchar(20) NOT NULL,
  `faq_question` varchar(500) NOT NULL,
  `faq_answer` longtext NOT NULL,
  `faq_i18n_status` tinyint(1) NOT NULL DEFAULT 1,
  `created` datetime NOT NULL DEFAULT current_timestamp(),
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_faq_i18n`),
  UNIQUE KEY `uq_faq_i18n_locale` (`id_faq`, `faq_locale`),
  KEY `idx_faq_i18n_company_locale` (`id_master_comp`, `faq_locale`, `faq_i18n_status`),
  KEY `idx_faq_i18n_faq_company` (`id_faq`, `id_master_comp`),
  CONSTRAINT `fk_faq_i18n_faq_company` FOREIGN KEY (`id_faq`, `id_master_comp`) REFERENCES `faq` (`id_faq`, `id_master_comp`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_faq_i18n_company` FOREIGN KEY (`id_master_comp`) REFERENCES `master_comp` (`id_master_comp`) ON UPDATE CASCADE,
  CONSTRAINT `chk_faq_i18n_status` CHECK (`faq_i18n_status` IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
