import { AsyncPipe } from '@angular/common';
import { Component, inject, input } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { Store } from '@ngxs/store';
import { filter, Observable, switchMap, take } from 'rxjs';
import { AdvanceDropdown } from '../../../shared/components/ui/advance-dropdown/advance-dropdown';
import { Button } from '../../../shared/components/ui/button/button';
import { ImageUpload } from '../../../shared/components/ui/image-upload/image-upload';
import { mediaConfig } from '../../../shared/data/media-config';
import { IAttachment } from '../../../shared/interface/attachment.interface';
import { ICategoryModel } from '../../../shared/interface/category.interface';
import { IProduct, IProductPayload, ProductMediaRole } from '../../../shared/interface/product.interface';
import { GetCategoriesAction } from '../../../shared/store/action/category.action';
import { CreateProductAction, EditProductAction, UpdateProductAction } from '../../../shared/store/action/product.action';
import { CategoryState } from '../../../shared/store/state/category.state';
import { ProductState } from '../../../shared/store/state/product.state';

@Component({selector:'app-form-product',imports:[AsyncPipe,ReactiveFormsModule,NgbModule,AdvanceDropdown,ImageUpload,Button],templateUrl:'./form-product.html',styleUrl:'./form-product.scss'})
export class FormProduct {
  private fb=inject(FormBuilder);private store=inject(Store);private route=inject(ActivatedRoute);private router=inject(Router);
  readonly type=input<string>('create');readonly mediaConfig=mediaConfig;
  categories$:Observable<ICategoryModel>=this.store.select(CategoryState.category);
  product:IProduct|null=null;id:string|null=null;activeTab='general';activeLocale:'id'|'en'='id';categoryIds:string[]=[];
  media:Partial<Record<ProductMediaRole,IAttachment|IAttachment[]|null>>={thumbnail:null,gallery:[],og:null};
  readonly form=this.fb.group({
    key:['',[Validators.required,Validators.pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)]],sku:['',Validators.required],product_type:['physical',Validators.required],status:['draft',Validators.required],unit:['pcs'],barcode:[''],manufacturer_code:[''],country_origin:['Indonesia'],hs_code:[''],is_featured:[false],sort_order:[0],
    weight_grams:[null as number|null],length_mm:[null as number|null],width_mm:[null as number|null],height_mm:[null as number|null],min_order_qty:[1,[Validators.required,Validators.min(0)]],lead_time_days:[null as number|null],manage_stock:[false],stock_quantity:[null as number|null],stock_status:['in_stock'],price_visibility:['contact'],internal_commerce_enabled:[false],
    id_slug:['',Validators.required],id_name:['',Validators.required],id_short_description:[''],id_description:[''],id_specifications:[''],id_meta_title:[''],id_meta_description:[''],id_canonical_url:[''],id_og_title:[''],id_og_description:[''],
    en_slug:['',Validators.required],en_name:['',Validators.required],en_short_description:[''],en_description:[''],en_specifications:[''],en_meta_title:[''],en_meta_description:[''],en_canonical_url:[''],en_og_title:[''],en_og_description:[''],
    prices:this.fb.array([]),marketplaces:this.fb.array([]),
  });
  get prices(){return this.form.controls.prices as FormArray;}get marketplaces(){return this.form.controls.marketplaces as FormArray;}
  ngOnInit(){this.store.dispatch(new GetCategoriesAction({locale:'id-ID'}));this.id=this.route.snapshot.paramMap.get('id');if(this.id)this.store.dispatch(new EditProductAction(this.id)).pipe(switchMap(()=>this.store.select(ProductState.selectedProduct)),filter((v):v is IProduct=>Boolean(v)),take(1)).subscribe(v=>this.patch(v));else this.addPrice();}
  setTab(tab:string){this.activeTab=tab;}selectCategories(ids:any[]){this.categoryIds=(ids??[]).map(String);}selectMedia(role:ProductMediaRole,value:any){this.media[role]=value;}
  addPrice(value:any={}){this.prices.push(this.fb.group({type:[value.type??'end_user',Validators.required],label:[value.label??''],currency:[value.currency??'IDR',Validators.required],amount:[value.amount??null,[Validators.required,Validators.min(0)]],compare_at:[value.compare_at??null],min_qty:[value.min_qty??null],max_qty:[value.max_qty??null],is_public:[value.is_public??true],is_active:[value.is_active??true]}));}
  addMarketplace(value:any={}){this.marketplaces.push(this.fb.group({provider:[value.provider??'shopee',Validators.required],label:[value.label??''],url:[value.url??'',[Validators.required,Validators.pattern(/^https?:\/\//i)]],sku:[value.sku??''],price:[value.price??null],currency:[value.currency??'IDR'],is_primary:[value.is_primary??false],is_active:[value.is_active??true]}));}
  remove(array:FormArray,index:number){array.removeAt(index);}
  submit(){this.form.markAllAsTouched();if(this.form.invalid){this.activeTab=this.invalidTab();return;}const payload=this.payload();const action=this.type()==='edit'&&this.id?new UpdateProductAction(payload,this.id):new CreateProductAction(payload);this.store.dispatch(action).subscribe({complete:()=>void this.router.navigateByUrl('/product')});}
  private parseSpecs(value:string){if(!value.trim())return null;try{return JSON.parse(value);}catch{return {text:value.trim()};}}
  private payload():IProductPayload{const v:any=this.form.getRawValue(),translation=(locale:'id-ID'|'en-US',p:'id'|'en')=>({locale,slug:v[`${p}_slug`]!,name:v[`${p}_name`]!,short_description:v[`${p}_short_description`]||'',description:v[`${p}_description`]||'',specifications:this.parseSpecs(v[`${p}_specifications`]||''),meta_title:v[`${p}_meta_title`]||'',meta_description:v[`${p}_meta_description`]||'',canonical_url:v[`${p}_canonical_url`]||'',og_title:v[`${p}_og_title`]||'',og_description:v[`${p}_og_description`]||'',status:1 as const});const media:any[]=[];for(const role of ['thumbnail','og'] as ProductMediaRole[]){const item=this.media[role] as IAttachment|null;if(item?.id_attachment)media.push({id:item.id_attachment,role,sort_order:0});}for(const [index,item] of ((this.media.gallery as IAttachment[])??[]).entries())if(item?.id_attachment)media.push({id:item.id_attachment,role:'gallery' as const,sort_order:index});return {key:v.key!,sku:v.sku!,product_type:v.product_type as any,status:v.status as any,unit:v.unit||null,barcode:v.barcode||null,manufacturer_code:v.manufacturer_code||null,country_origin:v.country_origin||null,hs_code:v.hs_code||null,weight_grams:v.weight_grams,length_mm:v.length_mm,width_mm:v.width_mm,height_mm:v.height_mm,min_order_qty:Number(v.min_order_qty)||1,lead_time_days:v.lead_time_days,manage_stock:v.manage_stock?1:0,stock_quantity:v.stock_quantity,stock_status:v.stock_status!,price_visibility:v.price_visibility as any,internal_commerce_enabled:v.internal_commerce_enabled?1:0,is_featured:v.is_featured?1:0,sort_order:Number(v.sort_order)||0,category_ids:this.categoryIds,media,prices:v.prices.map((x:any,i:number)=>({...x,label:x.label||null,sort_order:i})),marketplaces:v.marketplaces.map((x:any,i:number)=>({...x,label:x.label||null,sku:x.sku||null,sort_order:i})),translations:[translation('id-ID','id'),translation('en-US','en')]};}
  private patch(p:IProduct){const raw:any=p;this.product=p;this.categoryIds=(p.categories??[]).map(x=>String(x.id));const id=p.translations?.find(x=>x.locale==='id-ID'),en=p.translations?.find(x=>x.locale==='en-US');const value:any={key:p.key,sku:p.sku,product_type:raw.product_type,status:p.status,unit:raw.product_unit??p.unit,barcode:raw.product_barcode??p.barcode,manufacturer_code:raw.product_manufacturer_code??p.manufacturer_code,country_origin:raw.product_country_origin??p.country_origin,hs_code:raw.product_hs_code??p.hs_code,weight_grams:raw.product_weight_grams??p.weight,length_mm:raw.product_length_mm??p.length_mm,width_mm:raw.product_width_mm??p.width_mm,height_mm:raw.product_height_mm??p.height_mm,min_order_qty:raw.product_min_order_qty??p.min_order_qty,lead_time_days:raw.product_lead_time_days??p.lead_time_days,manage_stock:Boolean(raw.product_manage_stock??p.manage_stock),stock_quantity:raw.product_stock_quantity??p.stock_quantity,stock_status:p.stock_status,price_visibility:p.price_visibility,internal_commerce_enabled:Boolean(raw.product_internal_commerce_enabled??p.internal_commerce_enabled),is_featured:p.is_featured,sort_order:p.sort_order};for(const [prefix,t] of [['id',id],['en',en]] as const)if(t)Object.assign(value,{[`${prefix}_slug`]:t.slug,[`${prefix}_name`]:t.name,[`${prefix}_short_description`]:t.short_description,[`${prefix}_description`]:t.description,[`${prefix}_specifications`]:t.specifications?JSON.stringify(t.specifications,null,2):'',[`${prefix}_meta_title`]:t.meta_title,[`${prefix}_meta_description`]:t.meta_description,[`${prefix}_canonical_url`]:t.canonical_url,[`${prefix}_og_title`]:t.og_title,[`${prefix}_og_description`]:t.og_description});this.form.patchValue(value);this.prices.clear();(p.prices??[]).forEach(x=>this.addPrice(x));if(!this.prices.length)this.addPrice();this.marketplaces.clear();(p.marketplaces??[]).forEach(x=>this.addMarketplace(x));this.media.thumbnail=raw.product_thumbnail;this.media.gallery=raw.product_galleries??[];this.media.og=p.media?.find(x=>x.role==='og')??null;}
  private invalidTab(){if(['id_slug','id_name','en_slug','en_name'].some(k=>this.form.get(k)?.invalid))return'content';if(this.prices.invalid||this.marketplaces.invalid)return'channels';return'general';}
}